#!/usr/bin/env bash

options="  Shutdown
  Reboot
󰤄  Suspend
  Lock
󰍃  Log Out"

selected=$(echo -e "$options" | walker --dmenu -H)

case "$selected" in
*"Shutdown"*) systemctl poweroff ;;
*"Reboot"*) systemctl reboot ;;
*"Suspend"*) systemctl suspend ;;
*"Lock"*) bash ~/.local/share/quickshell-lockscreen/lock.sh ;;
*"Log Out"*) hyprctl dispatch 'hl.dsp.exit()' ;;
esac
