hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("GTK_IM_MODULE", "cedilla")
hl.env("QT_IM_MODULE", "cedilla")
hl.env("XCOMPOSEFILE", ".XCompose")
hl.env("HYPRSHOT_DIR", "Pictures/Screenshots")
