[general]
output-filename = "%Y-%m-%d-%H%M%S_satty.png"
save-after-copy = true
initial-tool = "arrow"
early-exit = true

[color-palette]
palette = [
    "#cc241d",
    "#98971a",
    "#d79921",
    "#458588",
    "#b16286",
    "#689d6a",
    "#282828",
    "#a89984",
]
custom = [
    "#fb4934",
    "#b8bb26",
    "#fabd2f",
    "#83a598",
    "#d3869b",
    "#8ec07c",
    "#928374",
    "#ebdbb2",
]
