wallpaper {
    monitor = eDP-1
    path = ~/Pictures/H0030-L387839767_original.JPG
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/H0030-L387839767_original.JPG
    fit_mode = cover
}

splash = false
