# -----------------------------------------------------------------------------
# Global Configs
# -----------------------------------------------------------------------------

# Uses .bashrc configs and starts faster
set -g default-command "${SHELL}"

# Enable Colours
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm*:Tc:sitm=\E[3m"

# Windows numbering
set -g base-index 1
set -g pane-base-index 1

# Enable Mouse
set -g mouse on

# Scrollback
set -g history-limit 50000

# Neovim CheckHealth Recommendations
set-option -sg escape-time 10
set-option -g focus-events on

# -----------------------------------------------------------------------------
# Bindings
# -----------------------------------------------------------------------------

# Enables Home/End Keys
bind -n Home send Escape "OH"
bind -n End send Escape "OF"

# Prefix Key
unbind C-b
set -g prefix C-a

# VIM motions
set-window-option -g mode-keys vi
bind -T copy-mode-vi "v" send -X begin-selection
bind -T copy-mode-vi "y" send -X copy-selection

# Enable Mouse Dragging
unbind -T copy-mode-vi MouseDragEnd1Pane

# Split Windows
bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"

# Previous Window
unbind -
bind - last-window

# Manage marked panes
bind J join-pane
bind S swap-pane

# Reload Config
bind R source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

# Kill unattached sessions
bind K confirm-before -p "Kill all unattached sessions? (y/n)" \
"run-shell ~/.local/bin/tmux-kill-unattached.sh"

# Resize Panes
set -g @zoom_resize_block_msg "Resize blocked on zoomed mode!"
set -g @resize_if_not_zoomed 'if -F "#{window_zoomed_flag}" "display-message \"#{@zoom_resize_block_msg}\""'
bind -r h run-shell "tmux #{@resize_if_not_zoomed} 'resize-pane -L 5'"
bind -r j run-shell "tmux #{@resize_if_not_zoomed} 'resize-pane -D 5'"
bind -r k run-shell "tmux #{@resize_if_not_zoomed} 'resize-pane -U 5'"
bind -r l run-shell "tmux #{@resize_if_not_zoomed} 'resize-pane -R 5'"

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

# Main colors
set -g status-style bg=black
# Copy mode colors
setw -g mode-style "fg=black bg=yellow bold"
# Panes borders
set -g pane-border-style "fg=green"
set -g pane-active-border-style "fg=green"
# Statusbar
set -g status-position top
set -g status-justify left
set -g status-left-length 100
set -g status-left " #[fg=yellow]< #[fg=white]#S #[fg=yellow]> "
set -g status-right-length 100
set -g status-right "#[fg=green] #(whoami)@#H #[fg=white bold]TMUX #[fg=yellow]v#(tmux -V | cut -d' ' -f2) "
# Window status
setw -g window-status-current-format "#[fg=green bold] #I #W #F "
setw -g window-status-format "#[fg=yellow] #I #[fg=white]#W #[fg=yellow]#F "
set -g window-status-separator ""
setw -g window-status-bell-style "fg=black bg=yellow bold"
# Messages
set -g message-style "fg=black,bg=yellow bold"

# -----------------------------------------------------------------------------
# Pop-Ups
# -----------------------------------------------------------------------------

# LazyGit
bind g display-popup -d "#{pane_current_path}" -E -w 80% -h 80% -E lazygit

# -----------------------------------------------------------------------------
# Plugins
# -----------------------------------------------------------------------------

set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-yank"
set -g @plugin "christoomey/vim-tmux-navigator"

set -g @tmux_navigator_disable_when_zoomed "1"

# TPM Init
run "~/.config/tmux/plugins/tpm/tpm"
